config/routes.rb
Descubriendony::Application.routes.draw do
  
  
  resources :sitemap, :only =>:index
  get 'sitemap.xml',:controller =>"sitemap",:action =>"xml"

  resources :transportations

  resources :subscribers

 resources :pages

  mount Ckeditor::Engine => '/ckeditor'
  match "/activities/:category_id/:id" => "activities#show", via: :get
  match "/activities/search", via: :get
  resources :activities

  match "/admin/activities/:id/edit" => "activities#edit", via: :get
  match "/admin/activities/" => "admin#activities", via: :get
  match "/admin/categories/" => "admin#categories", via: :get
  match "/admin/categories/new" => "categories#new", via: :get
  match "/admin/categories/:id/edit" => "categories#edit", via: :get
  resources :categories

  
  match "/admin/pages/" => "admin#pages", via: :get
  match "/admin/pages/new" => "pages#new", via: :get
  match "/admin/pages/:id/edit" => "pages#edit", via: :get
  
  match "/admin/transportations/" => "admin#transportations", via: :get
  match "/admin/transportations/new" => "transportations#new", via: :get
  match "/admin/transportations/:id/edit" => "transportations#edit", via: :get
  
  
  
  
  resources :admin
  match "/site2" => "pages#sitemapIII", via: :get
  match "/site1" => "pages#sitemapII", via: :get
  match "/site" => "pages#sitemapI", via: :get
  
  match "/about-us" => "pages#about_us", via: :get
  match "/faqs" => "pages#faqs", via: :get
  match "/landing" => "pages#landing", via: :get
  match "/thankyou" => "pages#thankyou", via: :get

  root :to => "activities#index"

end

app/models/transportation.rb
class Transportation
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name
  field :transport_type
  field :city

  belongs_to :activity
  has_and_belongs_to_many :lines, inverse_of: nil
end

app/controllers/transportations_controller.rb
class TransportationsController < ApplicationController
  before_action :set_transportation, only: [:show, :edit, :update, :destroy]

  # GET /transportations
  # GET /transportations.json
  def index
    city = get_city
    @transportations = Transportation.where(city: city)
  end

  # GET /transportations/1
  # GET /transportations/1.json
  def show
  end

  # GET /transportations/new
  def new
    city = get_city
    @transportation = Transportation.new(city: city)

  end

  # GET /transportations/1/edit
  def edit
    city = get_city
    @lines = Line.where(city: city)
  end

  # POST /transportations
  # POST /transportations.json
  def create
    city = get_city
    @transportation = Transportation.new(transportation_params)
    @transportation.city = city

    respond_to do |format|
      if @transportation.save
        format.html { redirect_to("/admin/transportations?city=#{city}", notice: 'Transportation was successfully created.' ) }
        format.json { render action: 'show', status: :created, location: @transportation }
      else
        format.html { render action: 'new' }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transportations/1
  # PATCH/PUT /transportations/1.json
  def update
     @transportation = Transportation.find(params[:id])
     @transportation.name = transportation_params[:name]
     @transportation.transport_type = transportation_params[:transport_type]
     @transportation.city = get_city
     @transportation.lines = transportation_params[:line_ids]
    if params[:line_ids]
      params[:line_ids].each do |ti|
        @transportation.lines.push(Line.find(ti))
      end
    end

    respond_to do |format|
      if @transportation.update
        format.html { redirect_to("/admin/transportations", notice: 'Transportation was successfully updated.' ) }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transportations/1
  # DELETE /transportations/1.json
 def destroy
    @transportation = Transportation.find(params[:id])
    @transportation.destroy
    render :json => { "message" => "ok" }, :status => 201
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transportation
      @transportation = Transportation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transportation_params
      params.require(:transportation).permit(:name, :transport_type, :city, :line_ids)
    end
end

app/views/transportations/_form.html.erb
<%= form_for(@transportation) do |f| %>
  <% if @transportation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transportation.errors.count, "error") %> prohibited this transportation from being saved:</h2>

      <ul>
      <% @transportation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transportations/edit.html.erb
<h1>Editing transportation</h1>

<%= form_for(@transportation) do |f| %>
  <% if @transportation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transportation.errors.count, "error") %> prohibited this transportation from being saved:</h2>

      <ul>
      <% @transportation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <br>

  <label> Add stations
  <ul>
  <% @lines.each do |line| %>
    <li>
      <%= check_box_tag "[line_ids][]", line.id, @transportation.lines.include?(line) %>
      <%= line.name %>
    </li>
  <% end %>
</ul>
</label>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', admin_transportations_path %>

app/views/transportations/new.html.erb
<h1>New transportation</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_transportations_path %>