config/routes.rb
Descubriendony::Application.routes.draw do
  
  
  resources :sitemap, :only =>:index
  get 'sitemap.xml',:controller =>"sitemap",:action =>"xml"

  resources :transportations

  resources :subscribers

 resources :pages

  mount Ckeditor::Engine => '/ckeditor'
  match "/activities/:category_id/:id" => "activities#show", via: :get
  match "/activities/search", via: :get
  resources :activities

  match "/admin/activities/:id/edit" => "activities#edit", via: :get
  match "/admin/activities/" => "admin#activities", via: :get
  match "/admin/categories/" => "admin#categories", via: :get
  match "/admin/categories/new" => "categories#new", via: :get
  match "/admin/categories/:id/edit" => "categories#edit", via: :get
  resources :categories

  
  match "/admin/pages/" => "admin#pages", via: :get
  match "/admin/pages/new" => "pages#new", via: :get
  match "/admin/pages/:id/edit" => "pages#edit", via: :get
  
  match "/admin/transportations/" => "admin#transportations", via: :get
  match "/admin/transportations/new" => "transportations#new", via: :get
  match "/admin/transportations/:id/edit" => "transportations#edit", via: :get
  
  
  
  
  resources :admin
  match "/site2" => "pages#sitemapIII", via: :get
  match "/site1" => "pages#sitemapII", via: :get
  match "/site" => "pages#sitemapI", via: :get
  
  match "/about-us" => "pages#about_us", via: :get
  match "/faqs" => "pages#faqs", via: :get
  match "/landing" => "pages#landing", via: :get
  match "/thankyou" => "pages#thankyou", via: :get

  root :to => "activities#index"

end

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page %>
    <%= f.text_field :page %>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
 
  
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/about_us.html.haml
.about-us
  .container
    %h1 About Us
    = raw @page.content_translations[I18n.locale.to_s]
    

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= form_for @page do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page %>
    <%= f.text_field :page, :disabled => true %>

    <%= f.label :city %>
    <%= f.text_field :city, :disabled => true %>
  </div>
 
  
  <div class="field">
    <%= f.label :content_English %><br>
    <%= cktext_area_tag :english_content, @page.content_translations["en"] %>
  </div>
  <div class="field">
    <%= f.label :content_Español %><br>
    <%= cktext_area_tag :spanish_content, @page.content_translations["es"] %>
  </div>
  <div class="field">
    <%= f.label :content_Português %><br>
    <%= cktext_area_tag :portuguese_content, @page.content_translations["pt"] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>





<%= link_to 'Back', admin_pages_path() %>

app/views/pages/faqs.html.haml
.faqs
  .container
    %h1 FAQs

    = raw @page.content
    

app/views/pages/landing.html.haml
.container

  %p
  %img{:alt => "", :src => "http://nuevayork.space/banners/accelerate/banner.jpg", :style => "height:100%; width:100%"}/
  %table{:style => "width:100%"}
  %tbody
  %tr
  %td{:style => "width:50%"}
  %p Buscas informaci&oacute;n sobre Nueva York, que hacer durante tu viaje, actividades, donde comer, los mejores sitios para visitar en un poco tiempo, actividades gratis o a bajo precio.
  

  / Begin MailChimp Signup Form
  %link{:href => "//cdn-images.mailchimp.com/embedcode/classic-10_7.css", :rel => "stylesheet", :type => "text/css"}
    :css
      #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif;  width:500px;}
      /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
         We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
    #mc_embed_signup{:style => "max-width: 100%;float: left;"}
      %form#mc-embedded-subscribe-form.validate{:action => "//descubriendonewyork.us13.list-manage.com/subscribe/post?u=133a2faa99b48a081d343abaf&amp;id=cbccd04d2e", :method => "post", :name => "mc-embedded-subscribe-form", :novalidate => "", :target => "_blank"}
        #mc_embed_signup_scroll
          %h2 Deseo más información sobre Nueva york
          .indicates-required
            %span.asterisk *
            indicates required
          .mc-field-group
            %label{:for => "mce-LNAME"} Nombre
            %input#mce-LNAME{:name => "LNAME", :type => "text", :value => ""}
          .mc-field-group
            %label{:for => "mce-EMAIL"}
              Email Address
              %span.asterisk *
            %input#mce-EMAIL.required.email{:name => "EMAIL", :type => "email", :value => ""}
          .mc-field-group
            %label{:for => "mce-FCIUDAD"} Ciudad / Pais
            %input#mce-FCIUDAD{:name => "FCIUDAD", :type => "text", :value => ""}
          .mc-field-group
            %label{:for => "mce-INFOSABER"} Informacion que desea saber
            %input#mce-INFOSABER{:name => "INFOSABER", :type => "text", :value => ""}
          #mce-responses.clear
            #mce-error-response.response{:style => "display:none"}
            #mce-success-response.response{:style => "display:none"}
          / real people should not fill this in and expect good things - do not remove this or risk form bot signups
          %div{"aria-hidden" => "true", :style => "position: absolute; left: -5000px;"}
            %input{:name => "b_133a2faa99b48a081d343abaf_cbccd04d2e", :tabindex => "-1", :type => "text", :value => ""}/
          .clear
            %input#mc-embedded-subscribe.button{:name => "subscribe", :type => "submit", :value => "Subscribe"}/
    %script{:src => "//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js", :type => "text/javascript"}
    :javascript
      (function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[2]='LNAME';ftypes[2]='text';fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FCIUDAD';ftypes[1]='text';fnames[5]='INFOSABER';ftypes[5]='text';}(jQuery));var $mcj = jQuery.noConflict(true);  
      / End mc_embed_signup
 
    %iframe{:frameborder => "0", :height => "315", :src => "https://www.youtube.com/embed/l3vcsHpVvs0", :style => "max-width: 100%; margin-top: 30px;", :width => "620"}
    %p Descubriendo New York te ayudara a organizae tu viaje, suscribete a nuestro newletter y te estamos enviando informaci&oacute;n sobre New York, o dejanos saber que necesitas y te ayudamos a planear tu propio viaje sin costo alguno            
   
   

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/thankyou.html.haml
.thankyou
  .container
    %h1 Thank you

    = raw @page.content
    